import { Metadata } from 'next';
import { Container } from '@/components/shared/Container';
import { Section } from '@/components/shared/Section';
import { site } from '@/data/site';
import { generatePageMetadata } from '@/lib/seo';

export const metadata: Metadata = generatePageMetadata({
  title: 'Payment Terms',
  description: `Payment terms and conditions for ${site.name}. Understand our payment methods, billing cycles, and accepted payment gateways.`,
  path: '/payment-terms',
});

export default function PaymentTermsPage() {
  return (
    <>
      <section className="pt-32 pb-10">
        <Container className="max-w-3xl">
          <h1 className="text-3xl font-bold font-[family-name:var(--font-heading)] mb-4">
            Payment Terms
          </h1>
          <p className="text-sm text-muted">Last updated: April 2025</p>
        </Container>
      </section>

      <Section className="pt-0">
        <Container className="max-w-3xl">
          <div className="space-y-8 text-muted text-sm leading-relaxed">
            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                1. Payment Methods
              </h2>
              <p>We accept the following payment methods:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>UPI (Google Pay, PhonePe, Paytm, BHIM, etc.)</li>
                <li>Bank Transfer (NEFT/RTGS/IMPS)</li>
                <li>Credit/Debit Cards (via payment gateway)</li>
                <li>Net Banking</li>
                <li>Razorpay / other integrated payment gateways</li>
              </ul>
              <p className="mt-2">
                All online payments are processed through secure, PCI-DSS compliant payment gateways. {site.name} does not store any card details or sensitive payment information on its servers.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                2. Payment Schedule
              </h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong className="text-foreground">Project-Based Services:</strong> Typically structured as:
                  <ul className="list-disc pl-6 mt-1 space-y-1">
                    <li>50% advance payment before project commencement</li>
                    <li>25% upon mid-project milestone delivery</li>
                    <li>25% upon final delivery and approval</li>
                  </ul>
                </li>
                <li>
                  <strong className="text-foreground">Monthly Retainer Services:</strong> Full month&apos;s payment due before the start of each billing cycle. Services include digital marketing, SEO, social media management, and maintenance plans.
                </li>
                <li>
                  <strong className="text-foreground">One-Time Services:</strong> Full payment due before delivery of final files/assets (logos, designs, brand kits, etc.).
                </li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                3. Invoice & Billing
              </h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>All invoices are generated by {site.legalName} and sent via email.</li>
                <li>Invoices include GST (Goods and Services Tax) as applicable under Indian law.</li>
                <li>Payment is due within 3 business days of invoice date unless otherwise agreed.</li>
                <li>Late payments beyond 7 days may attract a late fee of 2% per week on the outstanding amount.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                4. Currency
              </h2>
              <p>
                All prices and payments are in Indian Rupees (INR/₹) unless explicitly stated otherwise in the project proposal. For international clients, payments in USD or other currencies may be accepted at the prevailing exchange rate.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                5. Third-Party Costs
              </h2>
              <p>
                Any third-party costs (domain registration, hosting subscriptions, ad spend budgets, stock images, software licenses, etc.) are borne by the client and are not included in our service fees unless explicitly mentioned in the proposal. These are typically paid directly by the client or advanced by us and billed separately.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                6. Payment Gateway Compliance
              </h2>
              <p>
                All transactions processed through our website or payment links are handled by RBI-approved payment gateways. We comply with:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>RBI guidelines on digital payments</li>
                <li>PCI-DSS Level 1 compliance (via payment gateway partner)</li>
                <li>Data Protection Act compliance for payment data</li>
                <li>GST regulations for invoicing and tax collection</li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                7. Ownership & Delivery
              </h2>
              <p>
                All project deliverables (code, designs, content, etc.) remain the intellectual property of {site.legalName} until full payment is received. Upon receipt of complete payment, ownership transfers to the client as specified in the project agreement.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                8. Disputes
              </h2>
              <p>
                In case of payment disputes, please contact us at <a href={`mailto:${site.email}`} className="text-primary hover:text-primary-glow">{site.email}</a> within 7 days of the transaction. We will review and resolve disputes within 5-7 business days.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-bold text-foreground font-[family-name:var(--font-heading)] mb-3">
                9. Contact
              </h2>
              <p>
                For payment-related queries, contact:
              </p>
              <p className="mt-2">
                <strong className="text-foreground">{site.legalName}</strong><br />
                Address: {site.address.street}, {site.address.city}, {site.address.state} - {site.address.postalCode}, {site.address.country}<br />
                Email: <a href={`mailto:${site.email}`} className="text-primary hover:text-primary-glow">{site.email}</a><br />
                WhatsApp: <a href={`https://wa.me/${site.whatsapp.replace(/[^0-9]/g, '')}`} className="text-primary hover:text-primary-glow">{site.phone}</a>
              </p>
            </div>
          </div>
        </Container>
      </Section>
    </>
  );
}
